apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: tunes
provisioner: rancher.io/local-path
parameters:
  # This MUST match the path in your local-path-config exactly
  nodePath: /mnt/lab-backups/music-library
reclaimPolicy: Retain
volumeBindingMode: WaitForFirstConsumer