apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kavita
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/speddling/lwa-infra
    targetRevision: master
    path: services/kavita/kubernetes
  destination:
    server: https://kubernetes.default.svc
    namespace: kavita
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
